### ISSUE TITLE
Cannot build using sample code

### ISSUE THREAD

**Issue by MikeRobbieNZ** [buggins/ddbc#98]
I am new to D.  I have been testing out some of the languages capabilities and was very interested in ddbc

I get the following build error when using example code
C:\Users\micha\AppData\Local\dub\packages\ddbc-0.5.3\ddbc\source\ddbc\drivers\odbcddbc.d(333,24): Error: cannot implicitly convert expression `0` of type `int` to `void*`
C:\Users\micha\AppData\Local\dub\packages\ddbc-0.5.3\ddbc\source\ddbc\drivers\odbcddbc.d(334,24): Error: cannot implicitly convert expression `0` of type `int` to `void*`

The associated code in the odbcddbc.d file is
        SQLHENV henv = SQL_NULL_HENV;
        SQLHDBC conn = SQL_NULL_HDBC;

Being new to the language I have tried to cast and initiialise the variables,with no luck.

I cannot see any existing or past issues relating to this.  Any help would greatly appreciated!!

**Comment by SingingBush** [comment]
You can avoid this by using an older release of the D compiler. Also, are you planning to use ddbc with MS-SQL? Unless you are you don't need to include all the modules. For example, if you are using MySQL 5 (or Mariadb) then you could simply use `dub build --config=MySQL`. The ODBC code is going to need some changes to get it all working with dmd > 2.096, see #96

**Comment by MikeRobbieNZ** [comment]
Hi,

Thank you for your email. 

Perhaps this isn’t a new issue as obviously it’s a known change due to changes in the compiler.  Not the first time I have seen this. 

I have got MySQL native working now. 

Yes I am interested in MSSQL but can wait given so much work on these types of issues is voluntary. 

I am happy to close the issue and wait for progress. 

I didn’t originally look at D because of some of the negative info on the web about D. In fact this isn’t correct. 

Kind Regards 

Michael Roberts

**Comment by SingingBush** [comment]
D as a language is fine but it has a relatively small user base. This makes it tough to get contributors to projects such as this one. It's very frustrating to me as I'd like to use it more but I've ended up spending more time contributing to ddbc, [hibernated](https://github.com/buggins/hibernated), [mysql-native](https://github.com/mysql-d/mysql-native/), and the [Intellij D Language plugin](https://github.com/intellij-dlanguage/intellij-dlanguage) than I have working on my own D code.
